function buildITR1(user, taxResult) {
  const p = user.itrProfile || {};
  const addr = p.address || {};
  const bank = p.bankAccount || {};

  return {
    ITR: {
      ITR1: {
        _schemaNote: 'Simplified demo schema modeled on ITR-1 structure. Review against official AY schema before real filing.',
        CreationInfo: {
          SWVersionNo: 'FinChainAI-1.0',
          JSONCreatedBy: 'FinChain AI',
          JSONCreationDate: new Date().toISOString().slice(0, 10),
          IntermediaryCity: addr.city || '',
        },
        PersonalInfo: {
          AssesseeName: { FirstName: user.name || '' },
          PAN: p.pan || '',
          DOB: p.dob || '',
          Address: {
            ResidenceNo: addr.flatNo || '',
            ResidenceName: addr.premisesName || '',
            RoadOrStreet: addr.street || '',
            CityOrTownOrDistrict: addr.city || '',
            StateCode: addr.state || '',
            PinCode: addr.pincode || '',
            CountryCode: 'IN',
          },
        },
        FilingStatus: {
          AssessmentYear: p.assessmentYear || '2026-27',
          RegimeOpted: taxResult.recommended === 'new' ? 'New' : 'Old',
        },
        IncomeDeductions: {
          GrossTotalIncome: user.annualIncome || 0,
          Deduction80C: user.investments80C || 0,
          TotalTaxableIncome_OldRegime: Math.max(0, (user.annualIncome || 0) - (user.investments80C || 0) - 50000),
          TotalTaxableIncome_NewRegime: Math.max(0, (user.annualIncome || 0) - 75000),
        },
        TaxComputation: {
          TaxPayable_OldRegime: taxResult.oldRegimeTax,
          TaxPayable_NewRegime: taxResult.newRegimeTax,
          RecommendedRegime: taxResult.recommended,
          EstimatedSavings: taxResult.savings,
        },
        Refund: {
          BankAccountNo: bank.accountNo || '',
          IFSCCode: bank.ifsc || '',
          AccountType: bank.accountType || 'Savings',
        },
        Verification: {
          Declaration: 'This JSON is a pre-fill aid generated by FinChain AI. It is not a filed return. Review every field on the official portal before submission.',
        },
      },
    },
  };
}

module.exports = { buildITR1 };
